export const ColorPicker = 'ColorPicker'
export const ColorPickerBackgroundColor = 'ColorPickerBackgroundColor'
export const ColorPickerDark = 'ColorPickerDark'
export const ColorPickerLight = 'ColorPickerLight'
export const ColorPickerRectangle = 'ColorPickerRectangle'
export const ColorPickerSlider = 'ColorPickerSlider'
export const ColorPickerSliderThumb = 'ColorPickerSliderThumb'
export const Viewlet = 'Viewlet'
